$kind: http-request
name: Create New Role
url: "{{baseUrl}}/api/auth/organization/create-role"
method: POST
headers:
  Authorization: Bearer {{sessionToken}}
body:
  type: json
  content: "{\r

    \t\"role\": \"HR Coordinator\",\r

    \t\"permission\": {\r

    \t\t\"orders\": [\r

    \t\t\t\"create\",\r

    \t\t\t\"update\"\r

    \t\t],\r

    \t\t\"invitation\": [\r

    \t\t\t\"create\",\r

    \t\t\t\"cancel\"\r

    \t\t],\r

    \t\t\"member\": [\r

    \t\t\t\"read\",\r

    \t\t\t\"write\",\r

    \t\t\t\"delete\"\r

    \t\t]\r

    \t}\r

    }"
order: 4066602664766983
